// SPDX-License-Identifier: AGPL-3.0-only
// The host-owned Swift source compiled into every card dylib alongside the author's `Card.swift`
// — the card tier's SZRuntimeSupport. Card authors implement `SZCardMain.make(_:)` returning
// their root view; they must NOT redeclare the `@_cdecl` symbols or touch the raw struct.
//
// Everything the card can see or do goes through ONE object, `SZCardState`: the host pushes the
// node's scoped snapshot ("state") and a lossy display stream ("telemetry") in; the card streams
// gesture values out (`live` while the hand moves, `commit` once on release). Sizing is reported
// by the root wrapper below, so every card gets auto-size for free.
import Foundation

enum SZCardKit {
    /// Relative path the support file is written to inside a card's build dir.
    static let fileName = "SZCardKit.swift"

    static let source = """
    // HOST-OWNED. Generated by SZRuntime. Do not edit in a card.
    import Foundation
    import SwiftUI
    import AppKit

    typealias SZCardEmitFn = @convention(c) (UnsafeMutableRawPointer?, UnsafePointer<CChar>?, UnsafePointer<Float>?, Int32) -> Void
    typealias SZCardSizeFn = @convention(c) (UnsafeMutableRawPointer?, Float) -> Void

    // Must byte-match SZCardHostRaw in the host (SZCardABI.swift). Append-only.
    struct SZCardHostRaw {
        var apiVersion: Int32
        var hostContext: UnsafeMutableRawPointer?
        var liveFn: SZCardEmitFn?
        var commitFn: SZCardEmitFn?
        var sizeFn: SZCardSizeFn?
    }

    /// The card's window into its node: host-pushed observable state plus the outbound verbs.
    /// One instance per mounted card; SwiftUI observation drives re-render on every push.
    public final class SZCardState: ObservableObject {
        /// Node title from the scoped snapshot.
        @Published public private(set) var title: String = ""
        /// Raw decoded "state" payload — the scoped node projection (authors use the typed
        /// accessors below).
        @Published private(set) var state: [String: Any] = [:]
        /// Raw decoded "telemetry" payload — lossy, latest-wins.
        @Published private(set) var telemetry: [String: Any] = [:]

        private let raw: SZCardHostRaw
        init(raw: SZCardHostRaw) { self.raw = raw }

        func apply(channel: String, json: Data) {
            let decoded = (try? JSONSerialization.jsonObject(with: json)) as? [String: Any] ?? [:]
            switch channel {
            case "state":
                state = decoded
                title = decoded["title"] as? String ?? title
            case "telemetry":
                telemetry = decoded
            default:
                break
            }
        }

        /// Stream a continuous gesture value to `port` (runtime-only; the render sees it next
        /// frame, nothing is written to the project). Call on every drag tick.
        public func live(_ port: String, _ values: [Float]) { emit(raw.liveFn, port, values) }
        public func live(_ port: String, _ value: Double) { live(port, [Float(value)]) }
        public func live(_ port: String, _ values: [Double]) { live(port, values.map(Float.init)) }
        /// Commit a gesture's final value to `port` (one store write + persist per gesture).
        /// Call exactly once when the gesture ends.
        public func commit(_ port: String, _ values: [Float]) { emit(raw.commitFn, port, values) }
        public func commit(_ port: String, _ value: Double) { commit(port, [Float(value)]) }
        public func commit(_ port: String, _ values: [Double]) { commit(port, values.map(Float.init)) }
        /// Report measured intrinsic content height (points). The root wrapper feeds this.
        func reportSize(_ height: Double) { raw.sizeFn?(raw.hostContext, Float(height)) }

        private func emit(_ fn: SZCardEmitFn?, _ port: String, _ values: [Float]) {
            guard let fn = fn else { return }
            port.withCString { r in
                values.withUnsafeBufferPointer { fn(raw.hostContext, r, $0.baseAddress, Int32($0.count)) }
            }
        }
    }

    /// One projected port from the scoped node snapshot ("state" channel).
    public struct SZCardPort {
        public let name: String
        /// Contract type name: float, float2, float3, float4, colorRGB, colorRGBA, bool, string,
        /// enum, texture, floatArray, event.
        public let type: String
        let def: Any?
        public let uiMin: Double?
        public let uiMax: Double?
        public let uiStep: Double?

        init(_ raw: [String: Any]) {
            name = raw["name"] as? String ?? ""
            type = raw["type"] as? String ?? ""
            def = raw["default"]
            let ui = raw["ui"] as? [String: Any] ?? [:]
            uiMin = (ui["min"] as? NSNumber)?.doubleValue
            uiMax = (ui["max"] as? NSNumber)?.doubleValue
            uiStep = (ui["step"] as? NSNumber)?.doubleValue
        }

        /// The committed default as one number (float / bool as 0-1). Nil for vectors and strings.
        public var defaultDouble: Double? {
            if let n = def as? NSNumber { return n.doubleValue }
            return nil
        }
        /// The committed default as numbers: `[x, y]` for float2, `[r, g, b, a]` for colorRGBA…
        /// A scalar default reads as a one-element array. Empty when there is none.
        public var defaultDoubles: [Double] {
            if let n = def as? NSNumber { return [n.doubleValue] }
            return (def as? [Any])?.compactMap { ($0 as? NSNumber)?.doubleValue } ?? []
        }
        public var defaultString: String? { def as? String }
        public var defaultBool: Bool? { (def as? NSNumber)?.boolValue }
    }

    // Typed accessors over the raw channel payloads — the card-author surface.
    public extension SZCardState {
        var inputs: [SZCardPort] { (state["inputs"] as? [[String: Any]] ?? []).map(SZCardPort.init) }
        var outputs: [SZCardPort] { (state["outputs"] as? [[String: Any]] ?? []).map(SZCardPort.init) }
        func input(_ name: String) -> SZCardPort? { inputs.first { $0.name == name } }
        func output(_ name: String) -> SZCardPort? { outputs.first { $0.name == name } }

        /// Inputs currently driven by a wire — a card should show them but not fight them.
        var connectedInputs: Set<String> { Set(state["connectedInputs"] as? [String] ?? []) }

        /// The graph's render size in pixels (the output textures' size), for aspect math.
        var renderSize: CGSize? { Self.size(state["render"]) }
        /// The committed card-body footprint in points (what the host clips the card to).
        var bodySize: CGSize? { Self.size(state["body"]) }
        /// Where the host draws the node's live output thumbnail under the card, in card-body
        /// points (aspect-fit inside the body). Nil when the node has no backdrop (contract `card.backdrop`
        /// absent, live previews off, or no texture output). Overlay controls on top of this rect
        /// map 1:1 onto normalized output coordinates.
        var backdrop: CGRect? {
            guard let raw = state["backdrop"] as? [String: Any],
                  let x = (raw["x"] as? NSNumber)?.doubleValue, let y = (raw["y"] as? NSNumber)?.doubleValue,
                  let w = (raw["width"] as? NSNumber)?.doubleValue, let h = (raw["height"] as? NSNumber)?.doubleValue,
                  w > 0, h > 0 else { return nil }
            return CGRect(x: x, y: y, width: w, height: h)
        }

        /// Latest telemetry values for one of the node's float/floatArray OUTPUT ports (empty
        /// until the first frame arrives). ~30 Hz, lossy, latest-wins — display only.
        func values(_ port: String) -> [Double] {
            let outputs = telemetry["outputs"] as? [String: Any]
            return (outputs?[port] as? [Any])?.compactMap { ($0 as? NSNumber)?.doubleValue } ?? []
        }

        private static func size(_ raw: Any?) -> CGSize? {
            guard let raw = raw as? [String: Any],
                  let w = (raw["width"] as? NSNumber)?.doubleValue, let h = (raw["height"] as? NSNumber)?.doubleValue,
                  w > 0, h > 0 else { return nil }
            return CGSize(width: w, height: h)
        }
    }

    // The host-facing root around the author's view: measures the content's NATURAL height (the
    // card renders top-aligned inside the committed footprint, so growth is measurable while the
    // frame clips). Lives here so every card gets auto-size for free.
    struct SZCardRoot: View {
        let state: SZCardState
        let content: AnyView

        var body: some View {
            content
                .onGeometryChange(for: CGFloat.self) { proxy in
                    proxy.size.height
                } action: { height in
                    state.reportSize(Double(height))
                }
        }
    }

    // One live card instance: the state box + the hosting view whose lifetime bounds everything
    // dylib-defined that SwiftUI may retain.
    final class SZCardInstance {
        let state: SZCardState
        let hosting: NSHostingView<AnyView>
        @MainActor init(raw: SZCardHostRaw) {
            let state = SZCardState(raw: raw)
            self.state = state
            self.hosting = NSHostingView(rootView: AnyView(SZCardRoot(state: state, content: SZCardMain.make(state))))
        }
    }

    @_cdecl("SZCardAPIVersion")
    public func SZCardAPIVersion() -> Int32 { \(SZCardABI.version) }

    @_cdecl("SZCardCreate")
    public func SZCardCreate(_ hostRaw: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer? {
        guard let hostRaw = hostRaw else { return nil }
        let raw = hostRaw.assumingMemoryBound(to: SZCardHostRaw.self).pointee   // copy by value
        guard raw.apiVersion == \(SZCardABI.version) else { return nil }
        let instance = MainActor.assumeIsolated { SZCardInstance(raw: raw) }
        return Unmanaged.passRetained(instance).toOpaque()
    }

    @_cdecl("SZCardView")
    public func SZCardView(_ instance: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer? {
        guard let instance = instance else { return nil }
        let inst = Unmanaged<SZCardInstance>.fromOpaque(instance).takeUnretainedValue()
        return Unmanaged.passUnretained(inst.hosting as AnyObject).toOpaque()
    }

    @_cdecl("SZCardUpdate")
    public func SZCardUpdate(_ instance: UnsafeMutableRawPointer?, _ channel: UnsafePointer<CChar>?, _ json: UnsafePointer<UInt8>?, _ len: Int32) {
        guard let instance = instance, let channel = channel else { return }
        let inst = Unmanaged<SZCardInstance>.fromOpaque(instance).takeUnretainedValue()
        let data = (json != nil && len > 0) ? Data(bytes: json!, count: Int(len)) : Data()
        let name = String(cString: channel)
        MainActor.assumeIsolated { inst.state.apply(channel: name, json: data) }
    }

    @_cdecl("SZCardDestroy")
    public func SZCardDestroy(_ instance: UnsafeMutableRawPointer?) {
        guard let instance = instance else { return }
        // Release on main: the instance owns an NSView.
        MainActor.assumeIsolated {
            _ = Unmanaged<SZCardInstance>.fromOpaque(instance).takeRetainedValue()
        }
    }
    """
}
