// SPDX-License-Identifier: AGPL-3.0-only
// The host-owned SDK compiled into every step dylib beside the author's `Step.swift` — the
// `SZRuntimeSupport` pattern, step tier, ABI v4.
//
// P0 SPIKE NOTE: the source lives here as a string literal to prove the mechanics. The plan
// (P2) moves the static core to a real bundled `.swift` resource and renders the facts
// section from the one spec (`SZFacts.swift` in SZCore) via the SZFactGen plugin, so the
// same source compiles into both the app and every step. The `SZFacts` struct below is a
// placeholder for that generated section.
import Foundation

enum SZStepSDK {
    /// Relative path the SDK file is written to inside a step's build dir.
    static let fileName = "SZStepSDK.swift"

    static let source = """
    // HOST-OWNED. Generated by SZRuntime (step SDK, ABI v4). Do not edit in a step.
    import Foundation

    // MARK: - ABI (must byte-match SZStepABI.swift in the host)

    public typealias SZStepCompletionFn = @convention(c) (UnsafeMutableRawPointer?, Int32, UnsafePointer<CChar>?, Int32) -> Void
    public typealias SZStepAskReplyFn = @convention(c) (UnsafeMutableRawPointer?, Int32, UnsafePointer<CChar>?, Int32) -> Void
    public typealias SZStepAskFn = @convention(c) (UnsafeMutableRawPointer?, UnsafePointer<CChar>?, Int32, SZStepAskReplyFn?, UnsafeMutableRawPointer?) -> UInt64

    struct SZStepEvalRequestRaw {
        var apiVersion: Int32
        var factsJSON: UnsafePointer<CChar>?
        var factsLen: Int32
        var hostContext: UnsafeMutableRawPointer?
        var askFn: SZStepAskFn?
    }

    // MARK: - Facts (placeholder for the generated section from SZFacts.swift)

    /// The facts this evaluation was handed — one snapshot, pinned at evaluate-start. A step
    /// that awaits and then reads a fact sees the world as it was when evaluation began;
    /// needing fresher state is a graph-shape problem (two steps), not an SDK one.
    public struct SZFacts: Codable, Sendable {
        public var workLeft: Int?
        public var projectLoaded: Bool?
        public var draftedWork: Bool?
    }

    // MARK: - Errors

    public enum SZStepError: Error, CustomStringConvertible {
        /// The host offered no model capability to this evaluation.
        case modelUnavailable
        /// The host ran the completion and it failed (provider error, timeout).
        case modelFailed(String)
        /// The reply never decoded into the requested type, after every repair attempt.
        case schemaMismatch(template: String, detail: String)

        public var description: String {
            switch self {
            case .modelUnavailable: return "no model is available to this step"
            case .modelFailed(let reason): return "the model call failed: \\(reason)"
            case .schemaMismatch(let template, let detail):
                return "the reply to '\\(template)' never matched the expected shape: \\(detail)"
            }
        }
    }

    // MARK: - The context

    /// What one evaluation may touch: the facts snapshot, and one question-asking capability.
    /// `@unchecked Sendable`: the pointers are host-owned and valid until the evaluation's
    /// completion fires, which by construction outlives every use in the body.
    public struct SZContext: @unchecked Sendable {
        public let facts: SZFacts
        let host: UnsafeMutableRawPointer?
        let askFn: SZStepAskFn?

        // Typed views — a spelling over the same snapshot, not a second channel.
        public var project: Project { Project(facts: facts) }
        public var chat: Chat { Chat(facts: facts) }

        public struct Project {
            let facts: SZFacts
            /// How many nodes still need implementing.
            public var unimplementedCount: Int { facts.workLeft ?? 0 }
            /// Whether any work is left at all.
            public var hasWorkLeft: Bool { unimplementedCount > 0 }
            /// Whether a project is open at all.
            public var isLoaded: Bool { facts.projectLoaded ?? false }
        }

        public struct Chat {
            let facts: SZFacts
            /// Whether this chat turn left new unimplemented work behind.
            public var draftedWork: Bool? { facts.draftedWork }
        }

        /// Render `template` (a `.md.mustache` the host resolves against THIS evaluation's
        /// facts), run ONE stateless model completion, decode the reply into `T`. On a shape
        /// mismatch the host is asked again with the decode error attached (`repair`), up to
        /// `retries` more times. The model never sees more than the template names; the step
        /// never names a model — routing is the host's.
        public func askModel<T: Decodable>(template: String, as type: T.Type, retries: Int = 1) async throws -> T {
            var repair: SZAskRepair? = nil
            var lastDetail = "no reply"
            for attempt in 0...max(0, retries) {
                let reply = try await hostCompletion(SZAskRequest(template: template, attempt: attempt, repair: repair))
                do { return try SZJSONExtract.decode(type, from: reply) }
                catch {
                    lastDetail = String(describing: error)
                    repair = SZAskRepair(error: lastDetail, previousReply: reply)
                }
            }
            throw SZStepError.schemaMismatch(template: template, detail: lastDetail)
        }

        private func hostCompletion(_ request: SZAskRequest) async throws -> String {
            guard let askFn else { throw SZStepError.modelUnavailable }
            let json: String
            do {
                let data = try JSONEncoder().encode(request)
                json = String(decoding: data, as: UTF8.self)
            } catch { throw SZStepError.modelFailed("could not encode the ask request") }

            let box = SZReplyBox()
            // NOTE: no cancellation handler here — the ABI contract is that the HOST answers
            // every accepted call exactly once (status 1 when it cancels), so this
            // continuation always resolves. Cancellation needs no dylib-side plumbing.
            return try await withCheckedThrowingContinuation { continuation in
                box.continuation = continuation
                let boxPtr = Unmanaged.passRetained(box).toOpaque()
                let callID = json.withCString { bytes in
                    askFn(host, bytes, Int32(json.utf8.count), szReplyRelay, boxPtr)
                }
                if callID == 0 {
                    // Rejected: the reply will never fire; release our retain and settle.
                    Unmanaged<SZReplyBox>.fromOpaque(boxPtr).release()
                    box.take()?.resume(throwing: SZStepError.modelUnavailable)
                }
            }
        }
    }

    /// The ask request as the host receives it. Facts never travel back — the host renders
    /// the template against the same snapshot it handed this evaluation.
    public struct SZAskRequest: Codable, Sendable {
        public var template: String
        public var attempt: Int
        public var repair: SZAskRepair?
    }
    public struct SZAskRepair: Codable, Sendable {
        public var error: String
        public var previousReply: String
    }

    /// Tolerant decoding for CLI-shaped replies: try the bytes as-is, then every balanced
    /// JSON object/array inside them (fences, preambles, trailing prose), string-literal
    /// aware — a brace inside a quoted value neither closes nor opens anything. A candidate
    /// that fails keeps the scan moving to the next opener: models love restating the
    /// requested format ("answer in the form {json}") before the real answer.
    enum SZJSONExtract {
        static func decode<T: Decodable>(_ type: T.Type, from reply: String) throws -> T {
            let decoder = JSONDecoder()
            let whole = try? decoder.decode(type, from: Data(reply.utf8))
            if let whole { return whole }
            var bestError: Error?
            var searchStart = reply.startIndex
            while let start = reply[searchStart...].firstIndex(where: { $0 == "{" || $0 == "[" }) {
                if let end = balancedEnd(in: reply, from: start) {
                    let slice = Data(reply[start...end].utf8)
                    do { return try decoder.decode(type, from: slice) }
                    catch {
                        // A slice that PARSED as JSON but mismatched the shape is the useful
                        // diagnosis — prefer it over any prose-level parse error.
                        if bestError == nil,
                           (try? JSONSerialization.jsonObject(with: slice, options: [.fragmentsAllowed])) != nil {
                            bestError = error
                        }
                    }
                }
                searchStart = reply.index(after: start)
            }
            if let bestError { throw bestError }
            return try decoder.decode(type, from: Data(reply.utf8))   // throw the real error
        }

        /// The index of the closer balancing the opener at `start`, skipping string
        /// literals (with escape handling). nil if the reply never balances.
        static func balancedEnd(in reply: String, from start: String.Index) -> String.Index? {
            let opener = reply[start]
            let closer: Character = opener == "{" ? "}" : "]"
            var depth = 0
            var inString = false
            var escaped = false
            var index = start
            while index < reply.endIndex {
                let ch = reply[index]
                if inString {
                    if escaped { escaped = false }
                    else if ch == "\\\\" { escaped = true }
                    else if ch == "\\"" { inString = false }
                } else if ch == "\\"" {
                    inString = true
                } else if ch == opener {
                    depth += 1
                } else if ch == closer {
                    depth -= 1
                    if depth == 0 { return index }
                }
                index = reply.index(after: index)
            }
            return nil
        }
    }

    /// The parked ask: holds the continuation between the outbound call and the host's one
    /// guaranteed reply. The take() dance makes resumption idempotent by construction.
    final class SZReplyBox: @unchecked Sendable {
        let lock = NSLock()
        var continuation: CheckedContinuation<String, Error>?
        func take() -> CheckedContinuation<String, Error>? {
            lock.lock(); defer { lock.unlock() }
            let taken = continuation; continuation = nil; return taken
        }
    }

    private let szReplyRelay: SZStepAskReplyFn = { replyCtx, status, bytes, len in
        guard let replyCtx else { return }
        let box = Unmanaged<SZReplyBox>.fromOpaque(replyCtx).takeRetainedValue()
        let payload = bytes.map { String(decoding: UnsafeRawBufferPointer(start: $0, count: Int(len)), as: UTF8.self) } ?? ""
        switch status {
        case 0: box.take()?.resume(returning: payload)
        case 1: box.take()?.resume(throwing: CancellationError())
        default: box.take()?.resume(throwing: SZStepError.modelFailed(payload.isEmpty ? "unspecified" : payload))
        }
    }

    // MARK: - The authoring surface

    /// What a step answers with: the closed set the host draws as the card's ports and
    /// validates every edge against.
    public struct SZStepDeclaration: Encodable {
        public var outcomes: [String]
        public init(outcomes: [String]) { self.outcomes = outcomes }
    }

    /// The step contract: facts in, one declared outcome out. A body may `await` — and may
    /// `askModel` — but it cannot mutate the host; anything it wants done travels back as
    /// its outcome.
    public protocol SZStep: Sendable {
        var declaration: SZStepDeclaration { get }
        func evaluate(_ ctx: SZContext) async throws -> String
        func teardown()
    }
    public extension SZStep {
        func teardown() {}
        var declaration: SZStepDeclaration { SZStepDeclaration(outcomes: []) }
    }

    /// A yes/no question — the ordinary step, still one line:
    ///
    ///     let step = SZCondition { $0.project.hasWorkLeft }
    ///
    /// A synchronous closure converts implicitly; `try await` inside is equally at home.
    public struct SZCondition: SZStep {
        let body: @Sendable (SZContext) async throws -> Bool
        public init(_ body: @escaping @Sendable (SZContext) async throws -> Bool) { self.body = body }
        public var declaration: SZStepDeclaration { SZStepDeclaration(outcomes: ["yes", "no"]) }
        public func evaluate(_ ctx: SZContext) async throws -> String { try await body(ctx) ? "yes" : "no" }
    }

    /// A question whose answer IS data — one outcome per branch, named up front because the
    /// graph draws an edge from each:
    ///
    ///     let step = SZRouter("answer", "build") {
    ///         try await $0.askModel(template: "classify-reply", as: Ruling.self).kind
    ///     }
    public struct SZRouter: SZStep {
        let outcomes: [String]
        let body: @Sendable (SZContext) async throws -> String
        public init(_ outcomes: String..., answer: @escaping @Sendable (SZContext) async throws -> String) {
            self.outcomes = outcomes
            self.body = answer
        }
        public var declaration: SZStepDeclaration { SZStepDeclaration(outcomes: outcomes) }
        public func evaluate(_ ctx: SZContext) async throws -> String { try await body(ctx) }
    }

    // MARK: - Entry points

    private final class SZEvalTable: @unchecked Sendable {
        let lock = NSLock()
        var tasks: [UInt64: Task<Void, Never>] = [:]
        /// Tokens whose remove() beat their set() — a body that finished before
        /// SZStepEvaluate stored it. set() consumes the tombstone instead of resurrecting
        /// a finished entry, so the set stays ~empty.
        var orphaned: Set<UInt64> = []
        var nextToken: UInt64 = 1
        func mint() -> UInt64 { lock.lock(); defer { lock.unlock() }; let t = nextToken; nextToken += 1; return t }
        func set(_ token: UInt64, _ task: Task<Void, Never>) {
            lock.lock()
            if orphaned.remove(token) == nil { tasks[token] = task }
            lock.unlock()
        }
        func remove(_ token: UInt64) {
            lock.lock()
            if tasks.removeValue(forKey: token) == nil { orphaned.insert(token) }
            lock.unlock()
        }
        func cancel(_ token: UInt64) { lock.lock(); let task = tasks[token]; lock.unlock(); task?.cancel() }
    }
    private let szEvalTable = SZEvalTable()

    private func szDeliver(_ done: SZStepCompletionFn, _ ctx: UnsafeMutableRawPointer?, status: Int32, _ payload: String) {
        payload.withCString { done(ctx, status, $0, Int32(payload.utf8.count)) }
    }

    @_cdecl("SZStepAPIVersion")
    public func SZStepAPIVersion() -> Int32 { 4 }

    @_cdecl("SZStepEvaluate")
    public func SZStepEvaluate(_ raw: UnsafeRawPointer?, _ done: SZStepCompletionFn?, _ doneCtx: UnsafeMutableRawPointer?) -> UInt64 {
        guard let raw, let done else { return 0 }
        let request = raw.assumingMemoryBound(to: SZStepEvalRequestRaw.self).pointee
        guard let factsPtr = request.factsJSON, request.factsLen > 0,
              let facts = try? JSONDecoder().decode(SZFacts.self, from: Data(bytes: factsPtr, count: Int(request.factsLen)))
        else { return 0 }   // could not start; the completion is never called

        let ctx = SZContext(facts: facts, host: request.hostContext, askFn: request.askFn)
        let token = szEvalTable.mint()
        let task = Task {
            var status: Int32 = 0
            var payload = ""
            do { payload = try await step.evaluate(ctx) }
            catch is CancellationError { status = 1 }
            catch { status = 2; payload = String(describing: error) }
            // The table entry dies BEFORE the completion: once done() fires the host may
            // begin tearing this module down, so delivery is the body's last act.
            szEvalTable.remove(token)
            szDeliver(done, doneCtx, status: status, payload)         // exactly once, by construction
        }
        szEvalTable.set(token, task)
        return token
    }

    @_cdecl("SZStepCancel")
    public func SZStepCancel(_ token: UInt64) { szEvalTable.cancel(token) }

    @_cdecl("SZStepDeclare")
    public func SZStepDeclare(_ out: UnsafeMutablePointer<CChar>?, _ cap: Int32) -> Int32 {
        guard let out, !step.declaration.outcomes.isEmpty,
              let data = try? JSONEncoder().encode(step.declaration)
        else { return 0 }
        let bytes = Array(data)
        let n = min(bytes.count, Int(cap))
        for i in 0..<n { out[i] = CChar(bitPattern: bytes[i]) }
        return Int32(bytes.count)
    }

    @_cdecl("SZStepTeardown")
    public func SZStepTeardown() { step.teardown() }
    """
}
